---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventprocessor
  labels:
    app: cqrsapi
    component: eventprocessor
spec:
  selector:
    matchLabels:
      app: cqrsapi
      component: eventprocessor
  template:
    metadata:
      labels:
        app: cqrsapi
        component: eventprocessor
        lang: csharp
    spec:
      containers:
      - name: eventprocessor
        image: {{ print .Values.acr_name ".azurecr.io/cqrs/eventprocessor:" .Values.eventprocessor_version }}
        env:
        - name: AzureFunctionsJobHost__functions__0
          value: CommandProcessing
        envFrom:
        - secretRef:
            name: cqrssecrets
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: "0.5"
            memory: 128Mi
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: eventprocessor
spec:
  scaleTargetRef:
    name: eventprocessor
  minReplicaCount: 0
  maxReplicaCount: 3
  cooldownPeriod:  2 
  pollingInterval: 15
  triggers:
  - type: azure-eventhub
    metadata:
      connectionFromEnv: EVENTHUB_CONNECTIONSTRING
      storageConnectionFromEnv: AzureWebJobsStorage
---
