FROM golang:1.24-rc AS builder

WORKDIR /src
ENV GO111MODULE=on
COPY . .
RUN go mod tidy
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o /main .

FROM gcr.io/distroless/static-debian12:latest-amd64
COPY --from=builder /main ./
EXPOSE 8080
ENTRYPOINT ["./main" ]
