FROM golang:1.16.5 as builder

WORKDIR /src
ENV GO111MODULE=on
COPY . .
RUN go mod tidy
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o /main .

FROM scratch
COPY --from=busybox:1.28 /bin/busybox /bin/busybox
COPY --from=builder /src/ca-certificates.crt /etc/ssl/certs/
COPY --from=builder /main ./
EXPOSE 8081
ENTRYPOINT ["./main" ]
