FROM golang:1.10.3 as builder

WORKDIR $GOPATH/src 
COPY . ./
WORKDIR $GOPATH/src/cmd

RUN go get github.com/rs/cors
RUN go get github.com/gorilla/mux
RUN go get github.com/Azure/azure-event-hubs-go
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o /main .

FROM scratch
COPY --from=builder /main ./
EXPOSE 8081
ENTRYPOINT ["./main" ]